/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 badged.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/badged-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Curve001" geometry={nodes.Curve001.geometry} material={materials['SVGMat.001']} position={[0, 0, 0.23]} scale={10} />
        <mesh name="Curve002" geometry={nodes.Curve002.geometry} material={materials['SVGMat.001']} position={[0, 0, 0.23]} scale={10} />
        <mesh name="Curve003" geometry={nodes.Curve003.geometry} material={materials['SVGMat.001']} position={[0.22, 0, 0]} scale={10} />
        <mesh name="Curve004" geometry={nodes.Curve004.geometry} material={materials['SVGMat.001']} position={[0.22, 0, 0]} scale={10} />
        <mesh name="Curve005" geometry={nodes.Curve005.geometry} material={materials.Material} scale={10} />
        <mesh name="Curve006" geometry={nodes.Curve006.geometry} material={materials['Material.001']} position={[1.41, 0, -1.62]} scale={13.34} />
      </group>
    </group>
  )
}

useGLTF.preload('/badged-transformed.glb')
